line-length = 88

target-version = "py312"

exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "build",
    "dist",
]

[lint]

select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
]

ignore = [
    "E501",
]
