"""High-level improvement orchestration for QUANT AI Architect."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from ai_architect.analyzer.analysis_engine import AnalysisEngine
from ai_architect.core.context_builder import AnalysisContextBuilder
from ai_architect.improver.engine_facade import ImprovementEngineFacadeMixin
from ai_architect.patch_generator.patch_generator import PatchGenerator
from ai_architect.patch_generator.patch_validator import PatchValidator
from ai_architect.planner.planner import Planner
from ai_architect.providers.provider_manager import ProviderManager


class ImprovementEngine(ImprovementEngineFacadeMixin):
    """High-level improvement orchestrator."""

    def __init__(self) -> None:
        self.analysis = AnalysisEngine()
        self.context_builder = AnalysisContextBuilder()
        self.planner = Planner()
        self.provider = ProviderManager()

        self.patch_generator = PatchGenerator()

        # Compatibility aliases for the existing public API.
        self.builder = self.patch_generator.builder
        self.validator = PatchValidator()
        self.writer = self.patch_generator.writer

    def improve(
        self,
        repository: str | Path,
        instruction: str | None = None,
        file: str | None = None,
    ) -> dict[str, Any]:
        repository = Path(repository).resolve()

        if not repository.exists():
            return {
                "success": False,
                "repository": str(repository),
                "error": "Repository not found.",
            }

        if not repository.is_dir():
            return {
                "success": False,
                "repository": str(repository),
                "error": "Project path is not a directory.",
            }

        instruction = instruction or "Improve code quality"

        analysis = self.analysis.analyze(repository)

        context = self.context_builder.build_and_validate(
            str(repository),
            analysis,
        )

        if file is not None:
            context.put("target_file", file)

        plan = self.planner.build_plan(context)

        prompt = self._prompt(
            analysis=analysis,
            plan=plan,
            instruction=instruction,
            file=file,
        )

        improvement = self.generate(prompt)
        improvement = self._clean_diff(improvement)

        patch = self.build_patch(
            title="Automatic Improvement",
            description="Patch generated by QUANT AI Architect",
            diff=improvement,
        )

        structurally_valid = self.validate_structure(patch)

        # Structural validation is not approval.
        patch.approved = False

        output = self.save_patch(
            patch,
            repository,
        )

        return {
            "success": bool(structurally_valid),
            "approved": patch.approved,
            "structurally_valid": bool(structurally_valid),
            "patch": str(output),
            "patch_id": patch.id,
            "files": patch.total_files,
            "tasks": plan.total_tasks,
            "instruction": instruction,
            "target_file": file,
            "analysis": self.summary(analysis),
        }

    def _prompt(
        self,
        analysis: Any,
        plan: Any,
        instruction: str,
        file: str | None = None,
    ) -> str:
        summary = analysis.summary

        lines = [
            "You are QUANT AI Architect.",
            "",
            "Improvement Instruction",
            "=======================",
            instruction,
            "",
        ]

        if file is not None:
            lines.extend(
                [
                    "Target File",
                    "===========",
                    file,
                    "",
                ]
            )

        lines.extend(
            [
                "Project Summary",
                "===============",
                f"Files: {summary.total_files}",
                f"Python Files: {summary.python_files}",
                f"Classes: {summary.total_classes}",
                f"Functions: {summary.total_functions}",
                f"Dependencies: {summary.dependency_modules}",
                f"Duplicates: {summary.duplicate_groups}",
                f"Complexity: {summary.average_complexity}",
                "",
                "Recommendations",
                "===============",
            ]
        )

        lines.extend(
            f"- {recommendation}" for recommendation in analysis.recommendations
        )

        lines.extend(
            [
                "",
                "Execution Plan",
                "==============",
            ]
        )

        lines.extend(f"- {task.title}" for task in plan.tasks)

        lines.extend(
            [
                "",
                "Output Requirements",
                "====================",
                "Generate ONLY a unified diff patch.",
                "Do not explain.",
                "Do not include markdown.",
                "Do not wrap the patch in code fences.",
                "Return valid unified diff format.",
            ]
        )

        return "\n".join(lines)

    @staticmethod
    def _clean_diff(diff: str) -> str:
        if diff is None:
            return ""

        diff = str(diff).strip()

        if diff.startswith("```"):
            lines = diff.splitlines()

            if lines:
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            diff = "\n".join(lines)

        return diff.strip()

    def _register_patch_files(
        self,
        patch: Any,
        diff: str,
    ) -> None:
        if not diff:
            return

        for item in self._parse_diff_files(diff):
            path = str(item["path"])
            action = str(item["action"])
            additions = int(item["additions"])
            deletions = int(item["deletions"])

            if action == "CREATE":
                self.builder.add_created(
                    patch,
                    path,
                    additions,
                )

            elif action == "DELETE":
                self.builder.add_deleted(
                    patch,
                    path,
                )

            else:
                self.builder.add_modified(
                    patch,
                    path,
                    additions,
                    deletions,
                )

    @staticmethod
    def _parse_diff_files(
        diff: str,
    ) -> list[dict[str, Any]]:
        results: list[dict[str, Any]] = []
        current: dict[str, Any] | None = None

        for raw_line in diff.splitlines():
            line = raw_line.rstrip()

            if line.startswith("diff --git "):
                if current is not None:
                    results.append(current)

                current = {
                    "path": "",
                    "action": "MODIFY",
                    "additions": 0,
                    "deletions": 0,
                }

                match = re.match(
                    r"diff --git a/(.+?) b/(.+)$",
                    line,
                )

                if match:
                    current["path"] = match.group(2)

                continue

            if current is None:
                if line.startswith("--- "):
                    current = {
                        "path": "",
                        "action": "MODIFY",
                        "additions": 0,
                        "deletions": 0,
                    }
                else:
                    continue

            if line.startswith("new file mode"):
                current["action"] = "CREATE"
                continue

            if line.startswith("deleted file mode"):
                current["action"] = "DELETE"
                continue

            if line.startswith("+++ "):
                target = line[4:].strip()

                if target == "/dev/null":
                    current["action"] = "DELETE"

                elif target.startswith("b/"):
                    current["path"] = target[2:]

                elif not current["path"]:
                    current["path"] = target

                continue

            if line.startswith("--- "):
                source = line[4:].strip()

                if source == "/dev/null":
                    current["action"] = "CREATE"

                continue

            if line.startswith("+") and not line.startswith("+++"):
                current["additions"] += 1

            elif line.startswith("-") and not line.startswith("---"):
                current["deletions"] += 1

        if current is not None:
            results.append(current)

        return [item for item in results if item["path"]]
