"""High-level improvement orchestration for QUANT AI Architect."""

from __future__ import annotations

import os
import re
import time
from pathlib import Path
from typing import Any

from ai_architect.agents.agent_manager import AgentManager
from ai_architect.analyzer.analysis_engine import AnalysisEngine
from ai_architect.core.context_builder import AnalysisContextBuilder
from ai_architect.decision_engine.decision_engine import DecisionEngine
from ai_architect.git.git_manager import GitManager
from ai_architect.improver.engine_facade import ImprovementEngineFacadeMixin
from ai_architect.memory.memory_engine import MemoryEngine
from ai_architect.memory.models import ExperienceOutcome, ExperienceType
from ai_architect.patch_generator.patch_generator import PatchGenerator
from ai_architect.patch_generator.patch_validator import PatchValidator
from ai_architect.planner.planner import Planner
from ai_architect.providers.provider_manager import ProviderManager
from ai_architect.test_runner.test_runner import TestRunner


def auto_commit_activo() -> bool:
    """Whether the architect may commit on its own.

    Off unless explicitly enabled: committing modifies the user's repository,
    and that is not something to do by default. ``.env.example`` already
    shipped ``AUTO_COMMIT=false``; this is the code that honours it.
    """
    return os.getenv("AUTO_COMMIT", "false").strip().lower() == "true"


def run_tests_activo() -> bool:
    """Whether to run the target project's tests before deciding.

    On by default: deciding without running them is what the flow used to do,
    and it is worse. It can be turned off for a large repository whose suite
    is slow, at the cost of a much weaker decision.
    """
    return os.getenv("RUN_TESTS", "true").strip().lower() == "true"


class ImprovementEngine(ImprovementEngineFacadeMixin):
    """High-level improvement orchestrator."""

    def __init__(
        self,
        memory: MemoryEngine | None = None,
        git: GitManager | None = None,
        tests: TestRunner | None = None,
        agents: AgentManager | None = None,
    ) -> None:
        self.analysis = AnalysisEngine()
        self.context_builder = AnalysisContextBuilder()
        self.planner = Planner()
        self.provider = ProviderManager()

        self.patch_generator = PatchGenerator()

        # Memory of previous runs. Injectable so the tests can point it at a
        # temporary directory instead of writing into the real repository.
        self.memory = memory or MemoryEngine()

        # Turns "the patch is structurally valid" into "the patch is
        # acceptable", which are not the same thing.
        self.decision = DecisionEngine()

        # Injectable so the tests never touch a real repository. When it is
        # None, one is built for the repository being improved.
        self.git = git

        # Runs the target project's suite. Injectable so this project's own
        # tests do not spawn a pytest inside another pytest.
        self.tests = tests or TestRunner()

        # Only its static half is used here: security, dependencies, licences
        # and git, which cost nothing and enrich the decision.
        self.agents = agents or AgentManager()

        # Compatibility aliases for the existing public API.
        self.builder = self.patch_generator.builder
        self.validator = PatchValidator()
        self.writer = self.patch_generator.writer

    def improve(
        self,
        repository: str | Path,
        instruction: str | None = None,
        file: str | None = None,
    ) -> dict[str, Any]:
        repository = Path(repository).resolve()

        if not repository.exists():
            return {
                "success": False,
                "repository": str(repository),
                "error": "Repository not found.",
            }

        if not repository.is_dir():
            return {
                "success": False,
                "repository": str(repository),
                "error": "Project path is not a directory.",
            }

        instruction = instruction or "Improve code quality"

        comenzado = time.monotonic()

        analysis = self.analysis.analyze(repository)

        context = self.context_builder.build_and_validate(
            str(repository),
            analysis,
        )

        if file is not None:
            context.put("target_file", file)

        plan = self.planner.build_plan(context)

        prompt = self._prompt(
            analysis=analysis,
            plan=plan,
            instruction=instruction,
            file=file,
        )

        improvement = self.generate(prompt)
        improvement = self._clean_diff(improvement)

        patch = self.build_patch(
            title="Automatic Improvement",
            description="Patch generated by QUANT AI Architect",
            diff=improvement,
        )

        structurally_valid = self.validate_structure(patch)

        pruebas = self._ejecutar_pruebas(repository)

        inspeccion = self._inspeccionar(repository)

        # Structural validation is not approval: a well-formed patch can still
        # be a bad idea. The decision engine weighs the analysis metrics, the
        # findings, the size of the change and the state of the suite.
        #
        # Before, tests_ok carried `structurally_valid`, so the engine believed
        # the tests had passed when nothing had been run.
        decision = self.decision.decide(
            metrics=self.metrics(analysis),
            findings=[
                *self.recommendations(analysis),
                *self.agents.findings_de(inspeccion),
            ],
            task={
                "instruction": instruction,
                "files": patch.total_files,
                "tasks": plan.total_tasks,
                "structurally_valid": bool(structurally_valid),
            },
            tests_ok=bool(pruebas["success"]),
            repository=str(repository),
        )

        patch.approved = bool(decision.get("approved", False))

        output = self.save_patch(
            patch,
            repository,
        )

        commit = self._commit_si_procede(
            repository=repository,
            patch=patch,
            diff=improvement,
            instruction=instruction,
        )

        duracion = round(time.monotonic() - comenzado, 3)

        experiencia = self._recordar(
            repository=repository,
            file=file,
            instruction=instruction,
            structurally_valid=bool(structurally_valid),
            patch=patch,
            plan_tasks=plan.total_tasks,
            duracion=duracion,
            decision=decision,
            commit=commit,
        )

        return {
            "success": bool(structurally_valid),
            "approved": patch.approved,
            "structurally_valid": bool(structurally_valid),
            "patch": str(output),
            "patch_id": patch.id,
            "files": patch.total_files,
            "tasks": plan.total_tasks,
            "instruction": instruction,
            "target_file": file,
            "analysis": self.summary(analysis),
            "duration": duracion,
            "experience_id": experiencia,
            "decision": decision,
            "committed": commit["committed"],
            "commit_reason": commit["reason"],
            "tests": pruebas,
            "agents": inspeccion,
        }

    def _inspeccionar(self, repository: Path) -> dict[str, Any]:
        """Static inspection by the agents: security, dependencies, licences...

        Only the free half; the AI agents would mean five extra provider calls
        on every improvement. A failure here does not stop anything: the flow
        carries on with the analyzer's findings alone.
        """
        try:
            return self.agents.inspect(str(repository))
        except Exception as e:  # noqa: BLE001 - la mejora no depende de esto
            return {"error": str(e)}

    def _ejecutar_pruebas(self, repository: Path) -> dict[str, Any]:
        """Run the target project's suite and summarise the result.

        Running someone else's tests means running their code, and it can be
        slow, so it is behind ``RUN_TESTS`` (on by default). When it is off, or
        when the run itself fails, ``success`` is False: the decision engine
        then works with "the tests do not back this change", which is the
        prudent direction. Announcing a success that was never measured is
        exactly the bug this replaces.
        """
        if not run_tests_activo():
            return {
                "executed": False,
                "success": False,
                "reason": "RUN_TESTS desactivado",
                "passed": 0,
                "failed": 0,
            }

        try:
            resultado = self.tests.run(repository)
        except Exception as e:  # noqa: BLE001 - una suite ajena puede hacer de todo
            return {
                "executed": False,
                "success": False,
                "reason": f"no se pudieron ejecutar: {e}",
                "passed": 0,
                "failed": 0,
            }

        return {
            "executed": True,
            "success": bool(resultado.success),
            "reason": "suite en verde" if resultado.success else "la suite falla",
            "passed": resultado.passed,
            "failed": resultado.failed,
            "duration": resultado.duration,
        }

    def _commit_si_procede(
        self,
        *,
        repository: Path,
        patch: Any,
        diff: str,
        instruction: str,
    ) -> dict[str, Any]:
        """Apply and commit the patch, only when all three conditions hold.

        Committing modifies the user's repository, so it needs every guard:

        1. ``AUTO_COMMIT`` explicitly enabled -- off by default.
        2. The decision engine approved the patch.
        3. The target really is a git repository.

        A failure here does not break the improvement: the patch is already
        generated and saved on disk, and the user can apply it by hand. The
        reason is reported in the result.
        """
        if not auto_commit_activo():
            return {"committed": False, "reason": "AUTO_COMMIT desactivado"}

        if not patch.approved:
            return {"committed": False, "reason": "el parche no fue aprobado"}

        git = self.git or GitManager(repository)

        if not git.is_repository():
            return {"committed": False, "reason": "el destino no es un repositorio git"}

        try:
            if not git.apply_patch(diff):
                return {"committed": False, "reason": "el parche no se pudo aplicar"}

            mensaje = f"AI Architect: {instruction}".strip()

            if not git.commit(mensaje):
                return {"committed": False, "reason": "el commit fallo"}

        except Exception as e:  # noqa: BLE001 - el parche ya esta guardado
            return {"committed": False, "reason": f"error de git: {e}"}

        return {"committed": True, "reason": f"commit creado: {mensaje}"}

    def _recordar(
        self,
        *,
        repository: Path,
        file: str | None,
        instruction: str,
        structurally_valid: bool,
        patch: Any,
        plan_tasks: int,
        duracion: float,
        decision: dict[str, Any],
        commit: dict[str, Any],
    ) -> str | None:
        """Record the run in memory so future ones can learn from it.

        Recording must never break the improvement: if memory fails, the patch
        is already generated and saved, and losing one entry is not worth
        aborting for. The failure is reported in the result, not raised.
        """
        try:
            experiencia = self.memory.record(
                repository=str(repository),
                filename=file or "",
                instruction=instruction,
                provider=self.provider.name,
                outcome=(
                    ExperienceOutcome.SUCCESS
                    if structurally_valid
                    else ExperienceOutcome.FAILURE
                ),
                confidence=float(decision.get("confidence", 0.0)),
                experience_type=ExperienceType.EXECUTION,
                metadata={
                    "patch_id": patch.id,
                    "files": patch.total_files,
                    "tasks": plan_tasks,
                    "duration": duracion,
                    "decision": decision.get("decision"),
                    "approved": patch.approved,
                    "committed": commit["committed"],
                },
            )
        except Exception:  # noqa: BLE001 - la mejora ya esta hecha
            return None

        return str(experiencia.id)

    def _prompt(
        self,
        analysis: Any,
        plan: Any,
        instruction: str,
        file: str | None = None,
    ) -> str:
        summary = analysis.summary

        lines = [
            "You are QUANT AI Architect.",
            "",
            "Improvement Instruction",
            "=======================",
            instruction,
            "",
        ]

        if file is not None:
            lines.extend(
                [
                    "Target File",
                    "===========",
                    file,
                    "",
                ]
            )

        lines.extend(
            [
                "Project Summary",
                "===============",
                f"Files: {summary.total_files}",
                f"Python Files: {summary.python_files}",
                f"Classes: {summary.total_classes}",
                f"Functions: {summary.total_functions}",
                f"Dependencies: {summary.dependency_modules}",
                f"Duplicates: {summary.duplicate_groups}",
                f"Complexity: {summary.average_complexity}",
                "",
                "Recommendations",
                "===============",
            ]
        )

        lines.extend(
            f"- {recommendation}" for recommendation in analysis.recommendations
        )

        lines.extend(
            [
                "",
                "Execution Plan",
                "==============",
            ]
        )

        lines.extend(f"- {task.title}" for task in plan.tasks)

        lines.extend(
            [
                "",
                "Output Requirements",
                "====================",
                "Generate ONLY a unified diff patch.",
                "Do not explain.",
                "Do not include markdown.",
                "Do not wrap the patch in code fences.",
                "Return valid unified diff format.",
            ]
        )

        return "\n".join(lines)

    @staticmethod
    def _clean_diff(diff: str) -> str:
        if diff is None:
            return ""

        diff = str(diff).strip()

        if diff.startswith("```"):
            lines = diff.splitlines()

            if lines:
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            diff = "\n".join(lines)

        return diff.strip()

    def _register_patch_files(
        self,
        patch: Any,
        diff: str,
    ) -> None:
        if not diff:
            return

        for item in self._parse_diff_files(diff):
            path = str(item["path"])
            action = str(item["action"])
            additions = int(item["additions"])
            deletions = int(item["deletions"])

            if action == "CREATE":
                self.builder.add_created(
                    patch,
                    path,
                    additions,
                )

            elif action == "DELETE":
                self.builder.add_deleted(
                    patch,
                    path,
                )

            else:
                self.builder.add_modified(
                    patch,
                    path,
                    additions,
                    deletions,
                )

    @staticmethod
    def _parse_diff_files(
        diff: str,
    ) -> list[dict[str, Any]]:
        results: list[dict[str, Any]] = []
        current: dict[str, Any] | None = None

        for raw_line in diff.splitlines():
            line = raw_line.rstrip()

            if line.startswith("diff --git "):
                if current is not None:
                    results.append(current)

                current = {
                    "path": "",
                    "action": "MODIFY",
                    "additions": 0,
                    "deletions": 0,
                }

                match = re.match(
                    r"diff --git a/(.+?) b/(.+)$",
                    line,
                )

                if match:
                    current["path"] = match.group(2)

                continue

            if current is None:
                if line.startswith("--- "):
                    current = {
                        "path": "",
                        "action": "MODIFY",
                        "additions": 0,
                        "deletions": 0,
                    }
                else:
                    continue

            if line.startswith("new file mode"):
                current["action"] = "CREATE"
                continue

            if line.startswith("deleted file mode"):
                current["action"] = "DELETE"
                continue

            if line.startswith("+++ "):
                target = line[4:].strip()

                if target == "/dev/null":
                    current["action"] = "DELETE"

                elif target.startswith("b/"):
                    current["path"] = target[2:]

                elif not current["path"]:
                    current["path"] = target

                continue

            if line.startswith("--- "):
                source = line[4:].strip()

                if source == "/dev/null":
                    current["action"] = "CREATE"

                continue

            if line.startswith("+") and not line.startswith("+++"):
                current["additions"] += 1

            elif line.startswith("-") and not line.startswith("---"):
                current["deletions"] += 1

        if current is not None:
            results.append(current)

        return [item for item in results if item["path"]]
