"""
=========================================================
Execute Command

Institutional Execute Command
=========================================================
"""

from __future__ import annotations

from pathlib import Path

from ai_architect.execution.execution_engine import ExecutionEngine
from ai_architect.patch_generator.patch_loader import PatchLoader


def run(
    project: str,
    patch: str,
    dry_run: bool = False,
) -> dict:
    """
    Execute a validated patch against a repository.
    """

    repository = Path(project).resolve()
    patch_path = Path(patch).resolve()

    if not repository.exists():
        return {
            "success": False,
            "repository": str(repository),
            "error": "Repository not found.",
        }

    if not repository.is_dir():
        return {
            "success": False,
            "repository": str(repository),
            "error": "Project path is not a directory.",
        }

    if not patch_path.exists():
        return {
            "success": False,
            "repository": str(repository),
            "patch": str(patch_path),
            "error": "Patch file not found.",
        }

    if not patch_path.is_file():
        return {
            "success": False,
            "repository": str(repository),
            "patch": str(patch_path),
            "error": "Patch path is not a file.",
        }

    try:
        engine = ExecutionEngine()
        loader = PatchLoader()

        patch_object = loader.load(patch_path)

        if dry_run:
            return engine.dry_run(
                repository,
                patch_object,
            )

        return engine.execute(
            repository,
            patch_object,
        )

    except Exception as exc:
        return {
            "success": False,
            "repository": str(repository),
            "patch": str(patch_path),
            "error": str(exc),
        }


###############################################################
# Dry Run
###############################################################


def dry_run(
    project: str,
    patch: str,
) -> dict:
    return run(
        project=project,
        patch=patch,
        dry_run=True,
    )


###############################################################
# Information
###############################################################


def info() -> dict:
    engine = ExecutionEngine()

    return {
        "command": "execute",
        "description": "Execute a validated patch against the selected project.",
        "ready": engine.ready(),
        "version": engine.version(),
        "supports_dry_run": engine.supports_dry_run(),
    }


###############################################################
# Health
###############################################################


def health() -> dict:
    return ExecutionEngine().health()


###############################################################
# Configuration
###############################################################


def configuration() -> dict:
    return ExecutionEngine().configuration()


###############################################################
# Diagnostics
###############################################################


def diagnostics() -> dict:
    return ExecutionEngine().diagnostics()


###############################################################
# Statistics
###############################################################


def statistics() -> dict:
    return ExecutionEngine().statistics()


###############################################################
# Version
###############################################################


def version() -> str:
    return ExecutionEngine().version()


###############################################################
# Convenience
###############################################################


def __call__(
    project: str,
    patch: str,
    dry_run: bool = False,
) -> dict:
    return run(
        project=project,
        patch=patch,
        dry_run=dry_run,
    )


###############################################################
# CLI Metadata
###############################################################

COMMAND = {
    "name": "execute",
    "help": "Execute a validated patch generated by QUANT AI Architect.",
}


###############################################################
# Debug
###############################################################

if __name__ == "__main__":
    import json
    import sys

    if len(sys.argv) < 3:
        print("Usage: python execute.py <project> <patch>")
        raise SystemExit(1)

    print(
        json.dumps(
            run(
                project=sys.argv[1],
                patch=sys.argv[2],
            ),
            indent=4,
            default=str,
        )
    )
