"""
=========================================================
Patch Generator
=========================================================
"""

from __future__ import annotations

from pathlib import Path

from ai_architect.patch_generator.models import Patch
from ai_architect.patch_generator.patch_builder import PatchBuilder
from ai_architect.patch_generator.patch_writer import PatchWriter


class PatchGenerator:
    """
    Institutional Patch Generator.

    High-level coordinator responsible for building and
    persisting patches produced by AI Architect.

    Responsibilities

        • Create Patch objects
        • Register affected files
        • Store unified diff
        • Manage approval state
        • Validate patch structure
        • Persist patch artifacts

    This class NEVER edits the repository.

    It only builds and persists patch artifacts.
    """

    # ========================================================
    # Initialization
    # ========================================================

    def __init__(self) -> None:
        self.builder = PatchBuilder()
        self.writer = PatchWriter()

    # ========================================================
    # Patch Creation
    # ========================================================

    def create(
        self,
        title: str,
        description: str,
    ) -> Patch:
        """
        Create a new Patch.

        Newly created patches are always unapproved.
        """

        patch = self.builder.create(
            title=title,
            description=description,
        )

        patch.approved = False

        return patch

    # ========================================================
    # Files
    # ========================================================

    def add_created(
        self,
        patch: Patch,
        path: str,
        additions: int,
    ) -> None:
        self.builder.add_created(
            patch,
            path,
            additions,
        )

    def add_modified(
        self,
        patch: Patch,
        path: str,
        additions: int,
        deletions: int,
    ) -> None:
        self.builder.add_modified(
            patch,
            path,
            additions,
            deletions,
        )

    def add_deleted(
        self,
        patch: Patch,
        path: str,
    ) -> None:
        self.builder.add_deleted(
            patch,
            path,
        )

    # ========================================================
    # Diff
    # ========================================================

    def set_diff(
        self,
        patch: Patch,
        diff: str,
    ) -> None:
        """
        Store the unified diff generated by the provider.

        Approval is deliberately not changed here.
        """

        patch.diff = diff

    # ========================================================
    # Approval
    # ========================================================

    def approve(
        self,
        patch: Patch,
    ) -> None:
        """
        Explicitly approve a patch.
        """

        patch.approved = True

    def reject(
        self,
        patch: Patch,
    ) -> None:
        """
        Explicitly reject a patch.
        """

        patch.approved = False

    def is_approved(
        self,
        patch: Patch,
    ) -> bool:
        """
        Return the current approval state.
        """

        if patch is None:
            return False

        return bool(
            patch.approved,
        )

    # ========================================================
    # Persistence
    # ========================================================

    def save(
        self,
        patch: Patch,
        folder: str | Path,
    ) -> Path:
        """
        Persist the patch artifact.

        Approval state and unified diff are serialized by
        PatchWriter.
        """

        return self.writer.save(
            patch,
            folder,
        )

    # ========================================================
    # Validation
    # ========================================================

    @staticmethod
    def validate(
        patch: Patch,
    ) -> bool:
        """
        Basic structural validation.

        This does NOT require approval.

        Approval is an execution concern.
        """

        if patch is None:
            return False

        return patch.is_valid

    @staticmethod
    def validate_approved(
        patch: Patch,
    ) -> bool:
        """
        Validate that the patch is both structurally valid
        and explicitly approved.
        """

        if not PatchGenerator.validate(
            patch,
        ):
            return False

        return bool(
            patch.approved,
        )

    # ========================================================
    # Export
    # ========================================================

    def export(
        self,
        patch: Patch,
        folder: str | Path,
    ) -> dict:
        """
        Save the patch and return export metadata.
        """

        target = self.save(
            patch,
            folder,
        )

        return {
            "success": True,
            "patch_id": patch.id,
            "approved": patch.approved,
            "file": str(target),
            "files": patch.total_files,
            "additions": patch.total_additions,
            "deletions": patch.total_deletions,
        }

    def export_if_valid(
        self,
        patch: Patch,
        folder: str | Path,
    ) -> dict:
        """
        Persist the patch only when structurally valid.

        Approval is intentionally NOT required for persistence.
        Generated patches must be persisted before review.
        """

        if not self.validate(
            patch,
        ):
            return {
                "success": False,
                "error": "Patch validation failed.",
            }

        return self.export(
            patch,
            folder,
        )

    # ========================================================
    # Build
    # ========================================================

    def build(
        self,
        *,
        title: str,
        description: str,
        diff: str,
        folder: str | Path,
        approved: bool = False,
    ) -> dict:
        """
        Create, configure, validate and export a Patch.

        ``approved`` is explicit and defaults to False.
        """

        patch = self.create(
            title=title,
            description=description,
        )

        self.set_diff(
            patch,
            diff,
        )

        if approved:
            self.approve(
                patch,
            )

        return self.export_if_valid(
            patch,
            folder,
        )

    # ========================================================
    # Reset
    # ========================================================

    @staticmethod
    def clear(
        patch: Patch,
    ) -> None:
        """
        Clear generated modifications and reset approval.
        """

        if patch is None:
            return

        patch.files.clear()

        patch.diff = ""

        patch.approved = False

    # ========================================================
    # Information
    # ========================================================

    @staticmethod
    def has_changes(
        patch: Patch,
    ) -> bool:
        """
        Return True when the patch contains affected files.
        """

        if patch is None:
            return False

        return patch.total_files > 0

    @staticmethod
    def is_ready(
        patch: Patch,
    ) -> bool:
        """
        A patch is ready for review/export when it contains
        both affected files and a unified diff.

        Approval is deliberately excluded.
        """

        if patch is None:
            return False

        return (
            patch.total_files > 0
            and patch.has_diff
        )

    # ========================================================
    # Statistics
    # ========================================================

    @staticmethod
    def statistics(
        patch: Patch,
    ) -> dict:
        """
        Return patch statistics.
        """

        if patch is None:
            return {
                "files": 0,
                "additions": 0,
                "deletions": 0,
                "approved": False,
            }

        return {
            "files": patch.total_files,
            "additions": patch.total_additions,
            "deletions": patch.total_deletions,
            "approved": patch.approved,
        }

    # ========================================================
    # Summary
    # ========================================================

    @staticmethod
    def summary(
        patch: Patch,
    ) -> dict:
        if patch is None:
            return {
                "id": "",
                "title": "",
                "description": "",
                "approved": False,
                "files": 0,
                "additions": 0,
                "deletions": 0,
                "created_at": None,
            }

        return {
            "id": patch.id,
            "title": patch.title,
            "description": patch.description,
            "approved": patch.approved,
            "files": patch.total_files,
            "additions": patch.total_additions,
            "deletions": patch.total_deletions,
            "created_at": patch.created_at,
        }

    # ========================================================
    # Version
    # ========================================================

    @staticmethod
    def version() -> str:
        return "1.2"

    # ========================================================
    # Convenience
    # ========================================================

    def __call__(
        self,
        patch: Patch,
        folder: str | Path,
    ) -> Path:
        return self.save(
            patch,
            folder,
        )

    # ========================================================

    def __repr__(
        self,
    ) -> str:
        return (
            f"{self.__class__.__name__}"
            "(builder=PatchBuilder, "
            "writer=PatchWriter)"
        )

    # ========================================================

    def __str__(
        self,
    ) -> str:
        return "QUANT AI Architect Patch Generator"
